config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/help'

  devise_for :users

  resources :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :recipe

	validates_presence_of :name, :measurement
	# validates :unit_is_valid # i.e. validate unitwise understands it

end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :person
	belongs_to :recipe
	belongs_to :review

	validates_presence_of :person, :recipe
	validates :uniqueness # combination of person_id and recipe_id should be unique
end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :user
	has_many :meals
	has_many :recipes, through: :meals
	has_many :reviews, through: :meals

	validates_presence_of :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :meals
	has_many :people, through: :meals
	has_many :reviews, through: :meals
	has_many :ingredients, dependent: :destroy
	has_many :steps, dependent: :destroy

	validates_presence_of :name, :serving_size

  accepts_nested_attributes_for :steps, :ingredients

  private
  #TODO For future queued for warning messages with ingredients and steps
  def at_least_one? association
    errors.add(:base, "must add at least one #{association}") if association.blank?
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
	has_one :meal
	has_one :person, through: :meal
	has_one :recipe, through: :meal

	validates_presence_of :rating, :comment
	validates :rating, :between_one_and_five
	validates :comment, :minimum_length
end

app/models/step.rb
class Step < ActiveRecord::Base
	belongs_to :recipe
	has_many :images

	validates_presence_of :text

  acts_as_list scope: :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  expose(:recipes)
  expose(:recipe, attributes: :recipe_params)

  def create
    if recipe.save
      redirect_to recipe
      flash[:success] = "\"#{recipe.name}\" was successfully created"
    else
      render action: :new
    end
  end

  def update
    if recipe.save
      redirect_to recipe
      flash[:success] = "\"#{recipe.name}\" was successfully updated"
    else
      render action: :edit, id: recipe.id
    end
  end

  def destroy
    if recipe.destroy
      redirect_to recipes_path
      flash[:success] = "\"#{recipe.name}\" was successfully deleted"
    else
      render recipe
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :queued_for, :serving_size, steps_attributes: steps_params)
  end

  def steps_params
    [:id, :text]
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header

      %button.navbar-toggle.collapsed{ type: "button", "data-toggle" => "collapse", "data-target" => "#main-navbar-collapse" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path } Cookin' Meds

    #main-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{ :href => recipes_path } Recipes
      %ul.nav.navbar-nav.navbar-right
        %li
          -if signed_in?
            %a{:href => user_session_path } Log out
          -else
            %a{:href => new_user_session_path } Log in

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CookinMeds
    = favicon_link_tag 'favicon.ico'
    -#TODO add fav icon to title
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/navbar"
    .row
      .col-sm-1
      .col-sm-10
        .flash
        - flash.each do |key, value|
          %div{ :class => "alert alert-#{key}" }
            %a.close{ "data-dismiss" => "alert" } &times;
            %div{ :id => "flash_#{key}" }
              = value
        = yield

app/views/recipes/_form.html.haml
= form_for recipe do |f|
  .form-group
    = f.label :name, "Name"
    = f.text_field :name, class: "form-control", placeholder: "Recipe name"
  .form-group
    = f.label :serving_size, "Serving size"
    = f.text_field :serving_size, class: "form-control", placeholder: "Serving size"

  = f.submit :class => "btn btn-primary"

app/views/recipes/edit.html.haml
%h1 Edit Recipe
= render "form"

app/views/recipes/index.html.haml
%h1 Recipes
= link_to "New Recipe", new_recipe_path, class: "btn btn-primary"

app/views/recipes/new.html.haml
%h1 Create New Recipe
= render "form"

app/views/recipes/show.html.haml
%h1= recipe.name
%h4= "Serving size: #{recipe.serving_size}"
= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-primary"
= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger"

app/views/static_pages/help.html.haml
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.haml

app/views/static_pages/home.html.haml
%h1 Welcome to Cookin Meds!
%p Despite our unfortunately confusing title, we will be cooking Mediteranean dishes.

%button.btn.btn-default Button